export const data = [
  {
    id: '460',
    country_name: 'Nigeria',
    total_cases: '3',
    new_cases: '1',
    active_cases: '2',
    total_deaths: '',
    new_deaths: '',
    total_recovered: '1',
    serious_critical: '',
    region: null,
    total_cases_per1m: '',
    record_date: '2020-03-17',
  },
  {
    id: '14614',
    country_name: 'Nigeria',
    total_cases: '8',
    new_cases: '5',
    active_cases: '7',
    total_deaths: '',
    new_deaths: '',
    total_recovered: '1',
    serious_critical: '',
    region: null,
    total_cases_per1m: '0.04',
    record_date: '2020-03-18',
  },
  {
    id: '37814',
    country_name: 'Nigeria',
    total_cases: '12',
    new_cases: '4',
    active_cases: '11',
    total_deaths: '',
    new_deaths: '',
    total_recovered: '1',
    serious_critical: '',
    region: null,
    total_cases_per1m: '0.06',
    record_date: '2020-03-19',
  },
];
